version: 2
jobs:
  wakeTestServer:
    docker:
      - image: circleci/node:12.6.0-browsers
    environment:
      HEROKU_APP_NAME: test-armadillo-legs
    steps:
      - run:
          name: Ping test server
          command: curl -silent https://$HEROKU_APP_NAME.herokuapp.com/
  unitTest:
    docker:
      - image: circleci/node:12.6.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm run test:coverage
  deployTest:
    docker:
      - image: circleci/node:12.6.0
    environment:
      HEROKU_APP_NAME: test-armadillo-legs
    steps:
      - checkout
      - run:
          name: Deploy to test backend on Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run: sleep 10
      - run:
          name: Ping test deployment
          command: curl --fail https://$HEROKU_APP_NAME.herokuapp.com/

  deployDemo:
    docker:
      - image: circleci/node:12.6.0
    environment:
      HEROKU_APP_NAME: demo-armadillo-legs
    steps:
      - checkout
      - run:
          name: Deploy to demo backend on Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run: sleep 10
      - run:
          name: Ping demo deployment
          command: curl --fail https://$HEROKU_APP_NAME.herokuapp.com/
  deployProd:
    docker:
      - image: circleci/node:12.6.0
    environment:
      HEROKU_APP_NAME: armadillo-legs
    steps:
      - checkout
      - run:
          name: Deploy to production backend on Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run: sleep 10
      - run:
          name: Ping production deployment
          command: curl --fail https://$HEROKU_APP_NAME.herokuapp.com/
workflows:
  version: 2
  testAndDeploy:
    jobs:
      - wakeTestServer
      - unitTest
      - deployTest:
          requires:
            - unitTest
            - wakeTestServer
      - holdDemo:
          requires:
            - deployTest
      - deployDemo:
          requires:
            - holdDemo
      - holdProd:
          requires:
            - deployDemo
      - deployProd:
          requires:
            - holdProd
