version: 2
jobs:
  unitTest:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install npm
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules  
      - run: 
          name: Run unit tests
          command: npm run test
  deployTest:
      docker:
        - image: circleci/node:12.6.0
      environment:
        HEROKU_APP_NAME: test-armadillo-legs
      steps:
        - checkout
        - run:
            name: Deploy to test backend on Heroku
            command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
        - run:
            name: Wait for deployment to complete
            command: sleep(20)
        - run:
            name: Ping test deployment
            command: curl --fail https://HEROKU_APP_NAME.herokuapp.com/

  deployDemo:
      docker:
        - image: circleci/node:12.6.0
      environment:
        HEROKU_APP_NAME: demo-armadillo-legs
      steps:
        - checkout
        - run:
            name: Deploy to demo backend on Heroku
            command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master 
        - run:
            name: Wait for deployment to complete
            command: sleep(20)
        - run:
            name: Ping demo deployment
            command: curl --fail https://HEROKU_APP_NAME.herokuapp.com/
  deployProd:
      docker:
        - image: circleci/node:12.6.0
      environment:
        HEROKU_APP_NAME: armadillo-legs
      steps:
        - checkout
        - run:
            name: Deploy to production backend on Heroku
            command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
        - run:
            name: Wait for deployment to complete
            command: sleep(20)
        - run:
            name: Ping production deployment
            command: curl --fail https://HEROKU_APP_NAME.herokuapp.com/
  uiTest:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run: npm run cy:verify
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          command: npm run cy:run
workflows:
  version: 2
  testAndDeploy:
    jobs:
      - unitTest
      - deployTest:
          requires:
            - unitTest
      - uiTest:
          requires:
            - deployTest
      - deployDemo:
          requires:
            - uiTest
      - deployProd:
          type: approval
          requires:
            - deployDemo